const PALETTE = {
  PINK: ' #FF817E',
  PINK_LIGHT: '#FFC3C2',
  PINK_EXTRA_LIGHT: '#FCF5EE',

  GREY: '#E3E6EA',
  GREY_DARK: '#263A41',

  FOREGROUND: '#F9F9F9',
  BACKGROUND: '#FFFFFF',

  ERROR: '#F44336',

  WHITE: '#FFFFFF',
  BLACK: '#263A41',
}

export default PALETTE
