export { default as GetInTouch } from './get-in-touch'
export { default as Footer } from './footer'
export { default as Header } from './header'
export { default as Appointment } from './appointment'
export { default as Hero } from './hero'